AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  IamUser:
    Type: String
    Description: Full ARN for the IAM user used to deploy

Resources:

##############################################################################
# ELASTIC BEANSTALK
##############################################################################

  # the top-level beanstalk application. It deploys an ECS cluster in an
  # autoscaling group, and connects up an ELB.
  whodis:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: Whodis Elastic Beanstack

  # the beanstalk app configuration
  whodisConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref whodis
      Description: whodis Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '2'

      # important: the instance role configured on the ECS cluster instances.
      # This is defined below, and, among other things allows the instances to
      # pull from our ECR docker registry.
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref whodisInstanceProfile
      - Namespace: aws:autoscaling:updatepolicy:rollingupdate
        OptionName: RollingUpdateType
        Value: Immutable
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: ServiceRole
        Value: !Ref beanstalkServiceRole

      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced

      - Namespace: aws:elasticbeanstalk:healthreporting:system
        OptionName: SystemType
        Value: enhanced

      - Namespace: aws:elasticbeanstalk:application
        OptionName: Application Healthcheck URL
        Value: "/"

      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: StreamLogs
        Value: "true"

      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: DeleteOnTerminate
        Value: "true"

      SolutionStackName: 64bit Amazon Linux 2017.03 v2.7.3 running Multi-container Docker 17.03.1-ce (Generic)

  # the beanstalk environment. We only have one, but in a real app we would
  # likely want some dev/staging environments.
  whodisEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref whodis
      Description: whodis environment
      TemplateName: !Ref whodisConfigurationTemplate


##############################################################################
# DEPLOYMENT REPOSITORIES
##############################################################################

  # our ECR docker image registry: our build/deploy process pushes images
  # here, and then they are pulled by the ECS instances during deploy.
  whodisDockerRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "whodis"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          -
            Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                # Important: the parameterized IamUser we pass in is allowed
                # to push images to the registry.
                - !Ref IamUser
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"

  # bucket for app manifests
  whodisDeployBucket:
    Type: AWS::S3::Bucket


##############################################################################
# IAM
##############################################################################

  # the IAM service role used by Beanstalk to allow enhanced health checking
  beanstalkServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Action: 'sts:AssumeRole'
            Principal:
              Service:
                - "elasticbeanstalk.amazonaws.com"
            Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkEnhancedHealth
        - arn:aws:iam::aws:policy/service-role/AWSElasticBeanstalkService

  # the IAM role assigned to our Beanstalk-launched ECS instances.
  whodisRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Action: 'sts:AssumeRole'
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Effect: Allow
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
      Policies:
        -
          PolicyName: "ecs-service"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Sid: AllowEbAuth
                Effect: Allow
                Action:
                  - "ecs:CreateCluster"
                  - "ecs:DeregisterContainerInstance"
                  - "ecs:DiscoverPollEndpoint"
                  - "ecs:Poll"
                  - "ecs:RegisterContainerInstance"
                  - "ecs:StartTelemetrySession"
                  - "ecs:Submit*"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:BatchGetImage"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:GetAuthorizationToken"
                Resource:
                  - "*"

  whodisInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref whodisRole
